### ISSUE TITLE
Expose Typescript types

### ISSUE THREAD

**Issue by bluehat974** [lukemorales/query-key-factory#72]
Is it possible to expose all the type defined in this project.
I try to create a component which accept a DynamicFactoryOutput, but I can't import it at all as the type is defined privately

**Comment by lukemorales** [comment]
@bluehat974 not sure I follow because your props don't match the component example. Can you share a reproduction on a codepen/stackblitz? But on a superficial look, I don't think what you're trying to do is gonna work with the `DynamicFactoryOutput` type. With a example I can edit on codepen I can help you achieve what you're trying to do

**Comment by Tinoooo** [comment]
I also like to see exposed types. My use case on this is a helper function that creates query keys like so:

```typescript
export const createAllQueryKey = <TParametersGetAll>(): FactoryProperty /* is not available */ => ({
  workspaceId,
  fieldsToInclude = [],
  params,
}:
{
  workspaceId: MaybeRef<string>
  fieldsToInclude?: string[]
  params?: MaybeRef<TParametersGetAll>
},
) => ({
  queryKey: [
    workspaceId,
    ...fieldsToInclude,
    ...(params ? [params] : []),
  ],
  enabled: !!unref(workspaceId),
})

```

usage:
```typescript
export const queryKeys = createQueryKeys('my-key', {
  all: createAllQueryKey<ParametersGetAll>()
})
```

I have several keys in my project that have a similar structure. So such a helper would be handy.

@lukemorales Is this a valid use case for exposing the types or would you recommend a different solution?
